sudo: false
dist: xenial
language: cpp
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
    - valgrind
after_success:
  - cd test && bash <(curl -s https://codecov.io/bash)
env:
  matrix:
   - BUILD_CXX=0 CFLAGS="--coverage"
   - BUILD_CXX=1 CFLAGS="--coverage"
   - BUILD_CXX=0 CFLAGS="-O3"
   - BUILD_CXX=1 CFLAGS="-O3"
   - BUILD_CXX=0 TESTRUN_WRAPPER='valgrind -q --error-exitcode=126 --track-origins=yes --leak-check=full' CFLAGS="-O1 -g3" TESTRUN_NAME=memcheck
   - BUILD_CXX=1 TESTRUN_WRAPPER='valgrind -q --error-exitcode=126 --track-origins=yes --leak-check=full' CFLAGS="-O1 -g3" TESTRUN_NAME=memcheck
   - BUILD_CXX=0 CFLAGS="-g3 -fsanitize=undefined -fsanitize=address -fsanitize=leak"
   - BUILD_CXX=1 CFLAGS="-g3 -fsanitize=undefined -fsanitize=address -fsanitize=leak"
script:
 - make -C test clean && make -C test
